apiVersion: v1
kind: Namespace
metadata:
  name: discord-devops-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-devops-bot-agent
  namespace: discord-devops-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-devops-bot
  template:
    metadata:
      labels:
        app: discord-devops-bot
    spec:
      containers:
      - name: discord-devops-bot
        image: aboo/discord-devops-bot:latest
        imagePullPolicy: Always
        env:
        - name: Settings__TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-devops-bot
              key: TOKEN
        - name: Settings__CI_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: discord-devops-bot
              key: CI_CHANNEL_ID
        - name: Settings__IMPLEMENTATION_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: discord-devops-bot
              key: IMPLEMENTATION_CHANNEL_ID