name: Deploy
on:
  push:
    branches:
      - feature/pr-management

jobs:
    versioning:
        name: Versioning
        runs-on: ubuntu-latest
        steps:
          - name: Check out repo
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Identify this version
            uses: paulhatch/semantic-version@v4.0.2
            id: version
            with:
              bump_each_commit: true
          - name: Print version
            run: echo ${{ steps.version.outputs.version }}
        outputs:
            version: ${{ steps.version.outputs.version }}
    build_docker_image:
        name: Build Docker Image
        runs-on: ubuntu-latest
        needs: versioning
        steps:
          - name: Check out repo
            uses: actions/checkout@v2
          - name: Login to DockerHub
            uses: docker/login-action@v1 
            with:
                username: ${{ env.DOCKER_HUB_USERNAME }}
                password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
          - name: Build Docker Image and Push
            uses: docker/build-push-action@v2
            with:
                context: .
                file: ./Dockerfile
                push: true
                platforms: linux/amd64
                tags: ${{ env.DOCKER_HUB_USERNAME }}/discord-devops-bot:${{ needs.versioning.outputs.version }}
